selftests/cgroup: Fix build on older distros
On older distros struct clone_args does not have a cgroup member,
leading to build errors:

  cgroup_util.c: In function 'clone_into_cgroup':
  cgroup_util.c:343:4: error: 'struct clone_args' has no member named 'cgroup'

But the selftests already have a locally defined version of the
structure which is up to date, called __clone_args.

So use __clone_args which fixes the error.

Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>